name: my_build
on:
  workflow_dispatch: # 支持手动触发
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: true
      #     android: true
      #     dotnet: true
      #     haskell: true
      #     large-packages: true
      #     docker-images: true
      #     swap-storage: true


      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt build-dep .

      - name: Compile
        run: |
          make msm8916_defconfig
          make -j$(nproc)
          make -j$(nproc) deb-pkg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: custom-kernel
          path: |
            arch/arm64/boot/Image.gz
            arch/arm64/boot/dts/qcom/msm8916-wingtech-wt88047.dtb
            ../*.deb
