name: my_build
on:
  workflow_dispatch: # 支持手动触发
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          repository: msm8916-mainline/linux
          ref: msm8916/6.12.1

      - name: Get config
        run: |
          git clone --depth=1 https://github.com/myaccount3/Kernel-Compile-On-Action
          mv ./Kernel-Compile-On-Action/config ./.config
          rm -rf ./Kernel-Compile-On-Action

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev libelf-dev dwarves \
            fakeroot git debhelper libdw-dev

      - name: Generate config
        run: |
          make -j$(nproc) olddefconfig

      - name: View config
        run: |
          cat ./.config

      - name: Compile
        run: |
          make -j$(nproc)
          make -j$(nproc) bindeb-pkg

      - name: Workaround actions/upload-artifact
        run: |
          echo "artifacts_path=$(realpath ..)" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: custom-kernel
          path: |
            arch/arm64/boot/Image.gz
            arch/arm64/boot/dts/qcom/msm8916-wingtech-wt88047.dtb
            ${{ env.artifacts_path }}/*.deb
